version: '3'

networks:
  laravel:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_imijabar
    ports: 
      - "8090:80"
    volumes: 
      - ./src:/var/www/html
      - ./containers/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks:
      - laravel

  mysql:
    image: mariadb:latest
    container_name: mysql_imijabar
    restart: unless-stopped
    tty: true
    ports:  
      - "33066:3306"
    volumes:
      - ./containers/mysql:/var/lib/mysql
      - ./containers/mysql/templates:/root/templates
    environment:
      MYSQL_DATABASE: imijabar
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_imijabar
    volumes:
     - ./src:/var/www/html
    ports:
     - "9099:9000"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer_imijabar
    volumes:
      - ./src:/var/www/html
    depends_on:
      - app
    working_dir: /var/www/html
    networks:
      - laravel

  npm:
    image: node:14.17.0
    container_name: npm_imijabar
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan_imijabar
    volumes:
      - ./src:/var/www/html
    depends_on:
      - app
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks:
      - laravel
